### ISSUE TITLE
Installation in README won't work

### ISSUE THREAD

**Issue by kai-cool-dev** [danielhoherd/plexdl#2]
Hey,
I wanted to try out this neat script but I didn't got it to install. Either is this a wrong description in the README.md or pipx isn't working as described.

OS: Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

Steps to reproduce:
1. Install PIPX over PIP
```
pip install pipx
```

2. Clone Repo
```
git clone https://github.com/danielhoherd/plexdl.git
```

3. Try to install
```
pipx install --editable --spec="plexdl" plexdl
> --spec=plexdl should either be a path to a local project or a VCS url beginning with svn+, git+, hg+, or bzr+
```

Kind regards

**Comment by danielhoherd** [comment]
@kai-cool-dev sorry, I just saw this issue. I'm not sure what the problem is with pipx, but I replicated your issue. The version I saw available via PyPi was completely out of sync with what is available in github, so I don't know what's up there.

I updated the instructions with a simple pip3 installation, and I provided a method to run the app via docker, which is going to be your best bet for getting up and running quickly. Maybe I should put this into PyPi so it's easier to install...
