### ISSUE TITLE
Ability to download via URL instead of searching

### ISSUE THREAD

**Issue by LampPrinter** [danielhoherd/plexdl#43]
Is there any way where I can just pass the Plex media URL to this and it downloads the file?

**Comment by danielhoherd** [comment]
No, that's not what this tool is for. This tool is for searching for download URLs, which can then be used by other tools to do the actual downloading. Downloading is the easy part. Producing a downloadable URL from plex search parameters is the hard part part that this tool aims to solve.

One reason downloading is not supported in this tool is because it's possible the search would produce hundreds of results, comprising terabytes of media. You would not want to yolo download all of that. It would not be efficient, and it would be abusive to the people hosting the libraries that are being searched.
